### ISSUE TITLE
clone depth

### ISSUE THREAD

**Issue by msfjarvis** [halogenOS/android_packages_apps_Browser#1]
In place of doing `git commit --amend` each time, adding `clone-depth=1` in the manifest declaration for this repository will be more beneficial in case we need to revert a browser update

**Comment by xdevs23** [comment]
We should rather maintain a separate repository with all versions of the browser, and another one only with the latest.

**Comment by msfjarvis** [comment]
Lesser mortals are hereby notified that XOS lead developer Simao Gomes

## Viana has stated the moronic

Harsh 'MSF Jarvis' Shandilya

Hobbyist Android Platform and Application Developer.

**Comment by xdevs23** [comment]
We wanna reach 100 repositories anyways so @hbashton create a new one for this

**Comment by xdevs23** [comment]
![image](https://cloud.githubusercontent.com/assets/6959245/20067232/a0351c44-a514-11e6-916a-2e1dcf316085.png)
